baseURL = "http://piraeus.io"
languageCode = "en-us"
title = "Piraeus"
description = ""
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "alexzhc" # add your company name
  github = "https://github.com/alexzhc" # add your github profile name
  twitter = "" # add your twitter profile
  email = "alexzhc@hotmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "https://github.com/alexzhc/piraeus-appliance/blob/master/README.md"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "https://www.linbit.com/en/tech-blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = ""
